apiVersion: apps/v1
kind: Deployment
metadata:
  name: chew-and-cheer-app
  labels:
    app: chew-and-cheer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chew-and-cheer
  template:
    metadata:
      labels:
        app: chew-and-cheer
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - image: harbor.arpansahu.me/library/chew_and_cheer:latest
          name: chew-and-cheer
          envFrom:
            - secretRef:
                name: chew-and-cheer-secret
          ports:
            - containerPort: 8001
              name: gunicorn