apiVersion: v1
kind: Service
metadata:
  name: chew-and-cheer-service
spec:
  selector:
    app: chew-and-cheer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 32001
  type: NodePort