"""
Django settings for chew_and_cheer project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
from decouple import config
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
import django
from django.db.models.signals import pre_init

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# ============================ENV VARIABLES=====================================
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', cast=bool, default=False)
ALLOWED_HOSTS = config('ALLOWED_HOSTS').split(' ')

AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
BUCKET_TYPE = config('BUCKET_TYPE')

DATABASE_URL = config('DATABASE_URL')
REDIS_CLOUD_URL = config('REDIS_CLOUD_URL')

MAIL_JET_API_KEY = config('MAIL_JET_API_KEY')
MAIL_JET_API_SECRET = config('MAIL_JET_API_SECRET')
MAIL_JET_EMAIL_ADDRESS = config('MAIL_JET_EMAIL_ADDRESS')
MY_EMAIL_ADDRESS = config('MY_EMAIL_ADDRESS')

# Harbor Registry Configuration
HARBOR_URL = config('HARBOR_URL', default='harbor.arpansahu.space')
HARBOR_USERNAME = config('HARBOR_USERNAME')
HARBOR_PASSWORD = config('HARBOR_PASSWORD')

SENTRY_ENVIRONMENT = config('SENTRY_ENVIRONMENT')  # production Or "staging", "development", etc.
SENTRY_DSH_URL = config('SENTRY_DSH_URL')

PROJECT_NAME = 'chew_and_cheer'
USE_S3 = config('USE_S3', default=True, cast=bool)
# ===============================================================================

# Application definition
SITE_ID = 1
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modelling',
    'crud_django_form',
    'account',
    'crud_ajax',
    'rest_framework',
    'api',
    'rest_framework.authtoken',
    'django_filters',
    'graphene_django',
    'graph_ql_app',
    # 'graphql_jwt.refresh_token.apps.RefreshTokenConfig',
    # 'graphql_auth',
    'check_service_health',
    'django_test_enforcer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'chew_and_cheer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

WSGI_APPLICATION = 'chew_and_cheer.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': config('DB_NAME'),
#         'USER': config('DB_USER'),
#         'PASSWORD': config('DB_PASSWORD'),
#         'HOST': config('DB_HOST'),
#         'PORT': config('DB_PORT'),
#     }
# }

# Parse database configuration from $DATABASE_URL
import dj_database_url
# DATABASES['default'] =  dj_database_url.config()
#updated
DATABASES = {'default': dj_database_url.config(default=DATABASE_URL)}

# Set PostgreSQL schema for test database
if 'default' in DATABASES and DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
    # Merge OPTIONS to preserve any existing options and add search_path
    if 'OPTIONS' not in DATABASES['default']:
        DATABASES['default']['OPTIONS'] = {}
    DATABASES['default']['OPTIONS']['options'] = '-c search_path=chew_and_cheer,public'
    # Also set TEST database options to ensure schema is used during tests
    DATABASES['default']['TEST'] = {
        'NAME': 'test_arpansahu_one_db',
    }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# Password Reset

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # During development only

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'in-v3.mailjet.com'
EMAIL_HOST_USER = MAIL_JET_API_KEY
EMAIL_HOST_PASSWORD = MAIL_JET_API_SECRET
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = MAIL_JET_EMAIL_ADDRESS

PASSWORD_RESET_TIMEOUT = 60

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME':timedelta(minutes=10),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
#     'ROTATE_REFRESH_TOKENS':True,
# }

# Global Settings for Rest Framework - All View will be affected
# Global Settings can be overrided by Local
REST_FRAMEWORK = {
    # 'DEFAULT_AUTHENTICATION_CLASSES':['rest_framework.authentication.BasicAuthentication'],
    #     'DEFAULT_PERMISSION_CLASSES':['rest_framework.permissions.IsAuthenticated']
    # 'DEFAULT_AUTHENTICATION_CLASSES':['rest_framework.authentication.JWTAuthentication'],

    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'rest_framework.throttling.AnonRateThrottle',
    #     'rest_framework.throttling.UserRateThrottle',
    # ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '2/day',
        'user': '5/day',
        'jack': '3/minute',
        'viewitem': '5/hour',
        'modifyitem': '2/day',
    },
    # 'DEFAULT_FILTER_BACKENDS': [
    #     'django_filters.rest_framework.DjangoFilterBackend'
    # ]

    # 'SEARCH_PARAM': 'query'

    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 5

    # Disabling Browsable api
    # 'DEFAULT_RENDERER_CLASSES':(
    #     'rest_framework.renderers.JSONRenderer',
    # )

    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'
}

# GraphQl
# GRAPHENE = {
#     "SCHEMA": "graph_ql_app.schema.schema"
# }

# GRAPHENE = {
#     'MIDDLEWARE': [
#         'graphql_jwt.middleware.JSONWebTokenMiddleware',
#     ],
# }

# Authentication backend settings

AUTHENTICATION_BACKENDS = [
    # 'graphql_auth.backends.GraphQLAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# GRAPHQL_JWT = {
# 
#     # ...
#     "JWT_ALLOW_ANY_CLASSES": [
#         "graphql_auth.mutations.Register",
#         "graphql_auth.mutations.VerifyAccount",
#         "graphql_auth.mutations.ResendActivationEmail",
#         "graphql_auth.mutations.SendPasswordResetEmail",
#         "graphql_auth.mutations.PasswordReset",
#         "graphql_auth.mutations.ObtainJSONWebToken",
#         "graphql_auth.mutations.VerifyToken",
#         "graphql_auth.mutations.RefreshToken",
#         "graphql_auth.mutations.RevokeToken",
#         "graphql_auth.mutations.VerifySecondaryEmail",
#     ],
# 
#     "JWT_VERIFY_EXPIRATION": True,
#     "JWT_LONG_RUNNING_REFRESH_TOKEN": True,
# }

# Login_required Decorator
LOGIN_URL = 'accounts/login'
LOGOUT_URL = 'accounts/logout'


# Static files (CSS, JavaScript, Images)

if not USE_S3:
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    MEDIA_URL = '/media/'
else:
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='eu-north-1')
    
    AWS_S3_FILE_OVERWRITE = False  # Prevent overwriting files with the same name
    AWS_DEFAULT_ACL = None  # Ensure files are not public by default

    # Switch between MinIO and AWS S3
    if BUCKET_TYPE == 'MINIO':
        # MinIO/S3 Configuration
        AWS_QUERYSTRING_AUTH = False  # Don't add query parameters to URLs (use bucket policy instead)
        AWS_S3_SIGNATURE_VERSION = 's3v4'
        AWS_S3_USE_SSL = True
        AWS_S3_VERIFY = True
        AWS_S3_ADDRESSING_STYLE = 'path'  # Use path-style addressing for MinIO
        
        # MinIO API endpoint through nginx proxy
        AWS_S3_ENDPOINT_URL = 'https://minioapi.arpansahu.space'
        
        # Custom domain for serving files
        AWS_S3_CUSTOM_DOMAIN = f'minioapi.arpansahu.space/{AWS_STORAGE_BUCKET_NAME}'
    elif BUCKET_TYPE == 'AWS':
        AWS_S3_ENDPOINT_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
        AWS_S3_CUSTOM_DOMAIN = AWS_S3_ENDPOINT_URL

    # Static and Media File Storage Settings
    AWS_STATIC_LOCATION = f'portfolio/{PROJECT_NAME}/static'
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_STATIC_LOCATION}/'
    
    AWS_PUBLIC_MEDIA_LOCATION = f'portfolio/{PROJECT_NAME}/media'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_PUBLIC_MEDIA_LOCATION}/'
    
    AWS_PROTECTED_MEDIA_LOCATION = f'portfolio/{PROJECT_NAME}/protected'
    AWS_PRIVATE_MEDIA_LOCATION = f'portfolio/{PROJECT_NAME}/private'

    # Use custom storage classes with STORAGES dict (Django 4.2+)
    STORAGES = {
        'default': {
            'BACKEND': f'{PROJECT_NAME}.storage_backends.PublicMediaStorage',
            'OPTIONS': {
                'location': AWS_PUBLIC_MEDIA_LOCATION,
                'bucket_name': AWS_STORAGE_BUCKET_NAME,
                'endpoint_url': AWS_S3_ENDPOINT_URL,
                'access_key': AWS_ACCESS_KEY_ID,
                'secret_key': AWS_SECRET_ACCESS_KEY,
            },
        },
        'staticfiles': {
            'BACKEND': f'{PROJECT_NAME}.storage_backends.StaticStorage',
            'OPTIONS': {
                'location': AWS_STATIC_LOCATION,
                'bucket_name': AWS_STORAGE_BUCKET_NAME,
                'endpoint_url': AWS_S3_ENDPOINT_URL,
                'access_key': AWS_ACCESS_KEY_ID,
                'secret_key': AWS_SECRET_ACCESS_KEY,
            },
        },
        'private': {
            'BACKEND': f'{PROJECT_NAME}.storage_backends.PrivateMediaStorage',
            'OPTIONS': {
                'location': AWS_PRIVATE_MEDIA_LOCATION,
                'bucket_name': AWS_STORAGE_BUCKET_NAME,
                'endpoint_url': AWS_S3_ENDPOINT_URL,
                'access_key': AWS_ACCESS_KEY_ID,
                'secret_key': AWS_SECRET_ACCESS_KEY,
                'default_acl': 'private',
                'custom_domain': False,  # Disable custom domain for private files
            },
        },
    }

# Development settings (for local media/static handling)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static"), ]

# HTTP_X_FORWARDED_PROTO
SECURE_HSTS_SECONDS = 30  # Unit is seconds; *USE A SMALL VALUE FOR TESTING!*
SECURE_HSTS_SECONDS = 2_592_000  # 30 days
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# REFERRER POLICY
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

#Caching

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_CLOUD_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': PROJECT_NAME
    }
}

# Get the current git commit hash
def get_git_commit_hash():
    try:
        return subprocess.check_output(['git', 'rev-parse', 'HEAD']).decode('utf-8').strip()
    except Exception:
        return None

sentry_sdk.init(
    dsn=SENTRY_DSH_URL,
    integrations=[
            DjangoIntegration(
                transaction_style='url',
                middleware_spans=True,
                # signals_spans=True,
                # signals_denylist=[
                #     django.db.models.signals.pre_init,
                #     django.db.models.signals.post_init,
                # ],
                # cache_spans=False,
            ),
        ],
    traces_sample_rate=1.0,  # Adjust this according to your needs
    send_default_pii=True,  # To capture personal identifiable information (optional)
    release=get_git_commit_hash(),  # Set the release to the current git commit hash
    environment=SENTRY_ENVIRONMENT,  # Or "staging", "development", etc.
    # profiles_sample_rate=1.0,
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
        'sentry': {
            'level': 'ERROR',  # Change this to WARNING or INFO if needed
            'class': 'sentry_sdk.integrations.logging.EventHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'sentry'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'sentry'],
            'level': 'ERROR',  # Only log errors to Sentry
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console', 'sentry'],
            'level': 'ERROR',  # Only log errors to Sentry
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'sentry'],
            'level': 'WARNING',  # You can set this to INFO or DEBUG as needed
            'propagate': False,
        },
        # You can add more loggers here if needed
    },
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
    },
}

CSRF_TRUSTED_ORIGINS = ['https://school-chale-hum.arpansahu.me', ]
# Django 4.2 compatibility
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
