"""
UI Tests for chew_and_cheer - Django Test Enforcer
Generated on: 2026-02-13 17:54:03

These tests implement the stubs generated by django-test-enforcer.
Uses Playwright for browser automation.

Run with: pytest chew_and_cheer/test_ui.py --headed
"""
import pytest
from playwright.sync_api import Page, expect


class TestHomeUI:
    """UI tests for Home.html"""

    def test_crud_using_django_forms(self, authenticated_page: Page, base_url):
        """Test link: CRUD USING DJANGO FORMS"""
        authenticated_page.goto(f"{base_url}/home/")
        
        element = authenticated_page.locator(".btn, a:has-text('CRUD')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_crud_using_ajax(self, authenticated_page: Page, base_url):
        """Test link: CRUD USING AJAX AND JQUERY"""
        authenticated_page.goto(f"{base_url}/home/")
        
        element = authenticated_page.locator(".btn, a:has-text('AJAX')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_api_docs(self, authenticated_page: Page, base_url):
        """Test link: REST API DOCS"""
        authenticated_page.goto(f"{base_url}/home/")
        
        element = authenticated_page.locator(".btn, a:has-text('REST API'), a:has-text('API')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_unauthenticated_access(self, page: Page, base_url):
        """Test link: Login to View The Entire Home Page"""
        page.goto(f"{base_url}/home/")
        
        # Check if login link is present for unauthenticated users
        element = page.locator("a:has-text('Login'), .btn")
        if element.count() > 0:
            expect(element.first).to_be_visible()


