"""
UI Tests for crud_ajax - Django Test Enforcer
Generated on: 2026-02-13 17:54:03

These tests implement the stubs generated by django-test-enforcer.
Uses Playwright for browser automation.

Run with: pytest crud_ajax/test_ui.py --headed
"""
import pytest
from playwright.sync_api import Page, expect


class TestHomeUI:
    """UI tests for Home.html"""

    def test_submit(self, authenticated_page: Page, base_url):
        """Test button: SUBMIT"""
        authenticated_page.goto(f"{base_url}/ajax/")
        
        element = authenticated_page.locator(".btn, button:has-text('SUBMIT')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_edit(self, authenticated_page: Page, base_url):
        """Test button: EDIT"""
        authenticated_page.goto(f"{base_url}/ajax/")
        
        element = authenticated_page.locator(".btn, button:has-text('EDIT')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_delete(self, authenticated_page: Page, base_url):
        """Test button: DELETE"""
        authenticated_page.goto(f"{base_url}/ajax/")
        
        element = authenticated_page.locator(".btn, button:has-text('DELETE')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_forms_exist(self, authenticated_page: Page, base_url):
        """Test forms: addItem, updateItem, deleteItem"""
        authenticated_page.goto(f"{base_url}/ajax/")
        
        add_form = authenticated_page.locator("#addItem, form")
        if add_form.count() > 0:
            expect(add_form.first).to_be_attached()

    def test_input_fields(self, authenticated_page: Page, base_url):
        """Test input fields: name, description, price"""
        authenticated_page.goto(f"{base_url}/ajax/")
        
        name_input = authenticated_page.locator(".form-control, input[name='name'], #form-name")
        if name_input.count() > 0:
            expect(name_input.first).to_be_attached()

