"""
UI Tests for account - Django Test Enforcer
Generated on: 2026-02-13 17:54:03

These tests implement the stubs generated by django-test-enforcer.
Uses Playwright for browser automation.

Run with: pytest account/test_ui.py --headed
"""
import pytest
from playwright.sync_api import Page, expect


class TestRegisterUI:
    """UI tests for register.html"""

    def test_register_button(self, page: Page, base_url):
        """Test button: Register"""
        page.goto(f"{base_url}/register/")
        
        element = page.locator(".btn, button[type='submit']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_form(self, page: Page, base_url):
        """Test form: form_"""
        page.goto(f"{base_url}/register/")
        
        element = page.locator(".form-signin, form")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_input_email(self, page: Page, base_url):
        """Test input: inputEmail"""
        page.goto(f"{base_url}/register/")
        
        element = page.locator("#inputEmail, input[name='email']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_input_username(self, page: Page, base_url):
        """Test input: inputUsername"""
        page.goto(f"{base_url}/register/")
        
        element = page.locator("#inputUsername, input[name='username']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_input_password1(self, page: Page, base_url):
        """Test input: inputPassword1"""
        page.goto(f"{base_url}/register/")
        
        element = page.locator("#inputPassword1, input[name='password1']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_input_password2(self, page: Page, base_url):
        """Test input: inputPassword2"""
        page.goto(f"{base_url}/register/")
        
        element = page.locator("#inputPassword2, input[name='password2']")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestLoginUI:
    """UI tests for login.html"""

    def test_login_button(self, page: Page, base_url):
        """Test button: Login"""
        page.goto(f"{base_url}/login/")
        
        element = page.locator(".btn, button[type='submit']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_form(self, page: Page, base_url):
        """Test form: login form"""
        page.goto(f"{base_url}/login/")
        
        element = page.locator("form")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_input_username(self, page: Page, base_url):
        """Test input: inputUsername"""
        page.goto(f"{base_url}/login/")
        
        element = page.locator("#inputUsername, input[name='username']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_input_password(self, page: Page, base_url):
        """Test input: inputPassword"""
        page.goto(f"{base_url}/login/")
        
        element = page.locator("#inputPassword, input[name='password']")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestPasswordResetUI:
    """UI tests for password reset"""

    def test_reset_password_link(self, page: Page, base_url):
        """Test link: Reset password"""
        page.goto(f"{base_url}/login/")
        
        element = page.locator("a:has-text('Reset'), a:has-text('Forgot')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_join_us_link(self, page: Page, base_url):
        """Test link: Join Us"""
        page.goto(f"{base_url}/login/")
        
        element = page.locator("a:has-text('Join'), a:has-text('Register'), a:has-text('Sign up')")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestAccountUI:
    """UI tests for account.html"""

    def test_save_changes_button(self, authenticated_page: Page, base_url):
        """Test button: Save Changes"""
        authenticated_page.goto(f"{base_url}/account/")
        
        element = authenticated_page.locator(".btn, button:has-text('Save')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_form(self, authenticated_page: Page, base_url):
        """Test form: account form"""
        authenticated_page.goto(f"{base_url}/account/")
        
        element = authenticated_page.locator("form, .form-signin")
        if element.count() > 0:
            expect(element.first).to_be_visible()


