"""
UI Tests for crud_django_form - Django Test Enforcer
Generated on: 2026-02-13 17:54:03

These tests implement the stubs generated by django-test-enforcer.
Uses Playwright for browser automation.

Run with: pytest crud_django_form/test_ui.py --headed
"""
import pytest
from playwright.sync_api import Page, expect


class TestHomeUI:
    """UI tests for Home.html"""

    def test_add_button(self, authenticated_page: Page, base_url):
        """Test button: Add"""
        authenticated_page.goto(f"{base_url}/")
        
        element = authenticated_page.locator(".btn, button:has-text('Add'), a:has-text('Add')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_delete_button(self, authenticated_page: Page, base_url):
        """Test button: Delete"""
        authenticated_page.goto(f"{base_url}/")
        
        element = authenticated_page.locator(".btn, button:has-text('Delete')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_form(self, authenticated_page: Page, base_url):
        """Test form: form_"""
        authenticated_page.goto(f"{base_url}/")
        
        element = authenticated_page.locator("form, [data-testid='form']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_edit_link(self, authenticated_page: Page, base_url):
        """Test link: Edit"""
        authenticated_page.goto(f"{base_url}/")
        
        element = authenticated_page.locator(".btn, a:has-text('Edit')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_pagination_previous(self, authenticated_page: Page, base_url):
        """Test link: Previous"""
        authenticated_page.goto(f"{base_url}/")
        
        element = authenticated_page.locator(".page-link, a:has-text('Previous')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_pagination_next(self, authenticated_page: Page, base_url):
        """Test link: Next"""
        authenticated_page.goto(f"{base_url}/")
        
        element = authenticated_page.locator(".page-link, a:has-text('Next')")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestUpdateitemUI:
    """UI tests for updateitem.html"""

    def test_update_button(self, authenticated_page: Page, base_url):
        """Test button: Update"""
        # Note: This requires an item ID, checking if page loads
        authenticated_page.goto(f"{base_url}/")
        
        element = authenticated_page.locator("a:has-text('Edit')")
        if element.count() > 0:
            element.first.click()
            authenticated_page.wait_for_load_state("networkidle")
            
            update_button = authenticated_page.locator(".btn, button:has-text('Update')")
            if update_button.count() > 0:
                expect(update_button.first).to_be_visible()

    def test_form(self, authenticated_page: Page, base_url):
        """Test form: form_"""
        authenticated_page.goto(f"{base_url}/")
        
        element = authenticated_page.locator("a:has-text('Edit')")
        if element.count() > 0:
            element.first.click()
            authenticated_page.wait_for_load_state("networkidle")
            
            form = authenticated_page.locator("form, [data-testid='form']")
            if form.count() > 0:
                expect(form.first).to_be_visible()


